### ISSUE TITLE
Album view doesn't respect user order of subalbums

### ISSUE THREAD

**Issue by mmajchr** [Piwigo/Piwigo-Mobile#127] opened 2017-05-26 09:00 UTC
In my piwigo gallery I have all albums ordered. In root I have years 2016, 2017, etc. and in every of those albums month, in every month an album with photos from selected day. However in iOS mobile app in album tab I have a mishmash of all albums :( Finding a right one is really hard :(

**Comment by EddyLB** [comment] 2017-05-26 09:10
The albums of my gallery are also manually sorted and they appear as expected.
Could you please go to the Preferences tab, tap on Logout and then tap Login ?

**Comment by mmajchr** [comment] 2017-05-26 16:47
Nothing changed, even when I go to an album that app informs me has "15 sub-albums" I simply see NOTHING inside :D 😃

**Comment by EddyLB** [comment] 2017-05-26 16:54
Hum… Bizarre…
Have you checked the permissions of the photos with the web interface using Photos / Batch Manager and the permissions of the albums with Albums / Manage ?

**Comment by mmajchr** [comment] 2017-05-26 17:01
Nah I didn't check anything but "permissions" itself would explain why those "15 sub-albums" instead of being inside of main album are sitting next to it in main list ? 😄

**Comment by EddyLB** [comment] 2017-05-26 17:05
Can you send to my [private emai](mailto:piwigo@lelievre-berna.net)l the URL of your server and temporary credentials so that I can have a look ?

**Comment by mmajchr** [comment] 2017-05-26 17:57
Done, please check if that helps 😄

**Comment by EddyLB** [comment] 2017-05-27 16:37
Thank you for the informations. I checked as guest and using the credentials you provided on the web interface and with the iOS app.

As guest, I get the same albums and photos on both interfaces. When logged with the credentials, the web interface and the iOS app do not present the same albums. This is certainly due to the use of the Community extension installed on the Piwigo server. The iOS app is not compatible with this extension but we work on it (see issue #117).

With your credentials, you certainly encounter similar issues so I invite you to use the web interface until the Community extension becomes compatible with the iOS app. If you can, please contact the admin of the website to determine if he installed Community and let me know.

For the moment, I consider this reported issue as a duplicate of the issue #117.

**Comment by EddyLB** [comment] 2017-05-27 22:32
Duplicate confirmed. I therefore close this issue.

**Closed by EddyLB** 2017-05-27 22:32 UTC
Labels: duplicate
