### ISSUE TITLE
Automatic background uploading

### ISSUE THREAD

**Issue by exekutive** [Piwigo/Piwigo-Mobile#426] opened 2020-12-23 03:07 UTC
Sorry to open another topic about this, but may be this is new information.

I run an instance of Nextcloud on my server for various cloud functions. Nextcloud has an image library, and the mobile app has some really nice uploading/syncing features. (it's more of a media manager, not gallery, so it's not in the same category as Piwigo). The way I understand, it uses iOS location services to trigger background uploading (https://developer.apple.com/documentation/corelocation/cllocationmanager). It allows you to upload a certain album, or the entire image roll, and some other options. It works very nicely.  The Nextcloud server and mobile app is open source so the code is available (https://github.com/nextcloud/ios)

![image](https://user-images.githubusercontent.com/4755215/102954823-42642600-4489-11eb-97f7-e6593ad82f2a.png)

**Comment by EddyLB** [comment] 2020-12-24 08:05
Duplicate of #70

**Closed** 2021-08-11 15:43 UTC
Labels: duplicate

**Comment by EddyLB** [comment] 2021-10-13 11:41
The iOS app will pursue the upload if you let the iPhone/iPad connected to a Wi-Fi and a charger (no need to keep the app in the foreground). Background uploading is managed by the system and depends on priorities set by the system itself. So the uploads can be performed in the coming hours, during the next night or a few days later. This is decided by the system which establishes priorities based on your device and the app usage.

**Comment by EddyLB** [comment] 2021-10-13 15:44
The app uses the iOS [Background Tasks framework](https://developer.apple.com/documentation/backgroundtasks) which assumes that people connect their device to a charger when they sleep.

**Comment by xplosionmind** [comment] 2021-11-04 11:04
> The app uses the iOS [Background Tasks framework](https://developer.apple.com/documentation/backgroundtasks)

I know you can do little… still, I am reporting a very unstable experience with this feature.
