### ISSUE TITLE
[BETA 3.0] Feedback | Cache, offline capability, UI improvements

### ISSUE THREAD

**Issue by Phil353556** [Piwigo/Piwigo-Mobile#532] opened 2023-05-01 16:22 UTC
Hi, using the 3.0 beta via testflight, i navigate through my albums, photos and videos. (37,698 Photos, 1040 Albums)
Nothing special found except
**1/** about the application itself: the caches (see screenshots hereunder)   even wence the choice "_delete all_" is made, it seems that at least one  (_data_)  is not cleared.  I don't know if it is normal or not. I don't see any impact however.

![image](https://user-images.githubusercontent.com/64729485/235484798-82bddb4f-7e98-49c9-9d02-17448e9c613a.png)
![image](https://user-images.githubusercontent.com/64729485/235484841-112a5117-86bf-479c-8c68-841011771844.png)

**2/** "_bringing offline capability_." should it work?  because I got the following message:
![image](https://user-images.githubusercontent.com/64729485/235486739-c3250194-1800-4582-b849-2a8b970edc1c.png)

Kind regards
Phil

**Comment by EddyLB** [comment] 2023-05-02 07:28
Thank you for the feedback.

1. The problem is that force checkpointing fails to reliably empty the -wal file associated with the cache. Data is stamped as deleted but the cache is not emptied yet. The app calculates the amount of space taken by a cache which is not yet cleaned. This is an issue as it gives the impression that data is not erased. We are going to change the way we calculate the amount of stored data.
2. This error message appears once to inform the user that the app cannot get up-to-date image data. It should not appear again when browsing an album. I agree that this may lead to some incomprehension and we are going to change this.

**Comment by EddyLB** [comment] 2023-05-03 18:00
After thorough search, it is not possible to estimate properly the size of the cache in bytes. The app will therefore present the total number of objects in cache.

**Comment by rgischig** [comment] 2023-05-04 18:56
I've just installed the beta today. So far it't really working quite well, even when I turn the network off. Well done :-)

In the settings page for the Upload, I got a bit confused over the colors, initially I thought that the top box would be the "denied" services, due to the red "-" symbols. Maybe this can be somehow made more clear that the top box is the "allowed" and the lower one the "denied" section > see screenshot

![Photo 23-05-04 20-47-37 7730](https://user-images.githubusercontent.com/21161212/236301599-5a587fa6-4d7b-4906-a1cc-2f908a769053.png)

**Comment by rgischig** [comment] 2023-05-04 18:58
**Feature request: Multi-gallery-login**

As I own multiple galleries, it would be nice to either switch between them, withou the need of log-out each gallery

**Comment by rgischig** [comment] 2023-05-04 19:05
Feedback:
While "Updating..." a large folder (650 images), the UI is "jerky". Even once the update has finished, the UI is sluggish. 
Once you exit back out und in, it's butter-smooth.

iPhone 12Pro, on local Wifi and the server in house

**Comment by EddyLB** [comment] 2023-05-20 10:50
> Feedback: While "Updating..." a large folder (650 images), the UI is "jerky". Even once the update has finished, the UI is sluggish. Once you exit back out und in, it's butter-smooth.
> 
> iPhone 12Pro, on local Wifi and the server in house

This should be fixed in the version 3.0 build 514 of the app.

**Closed** 2023-06-27 16:35 UTC
