### ISSUE TITLE
Request: mobile sync

### ISSUE THREAD

**Issue by exekutive** [Piwigo/Piwigo-Mobile#379] opened 2020-06-26 18:32 UTC
It would be nice if the Piwigo app could automatically upload photos taken with the smartphone camera, the way Google and Apple does it. It makes sharing and backup much much easier.

**Comment by EddyLB** [comment] 2020-06-26 21:44
We are rewriting completely the management of uploads which shall be deployed in version 2.5 (see issue #31). The automatic upload of photos will come right after. I close this issue because it is a duplicate of #70.

**Closed by EddyLB** 2020-06-26 21:44 UTC
