### ISSUE TITLE
unable to display pictures and thumbnails folder with whitespace

### ISSUE THREAD

**Issue by unnilennium** [Piwigo/Piwigo-Mobile#220] opened 2018-04-12 19:12 UTC
Hi,
since update to 2.1.7 (and maybe a few version before, I have not open my album since a few months) the albums with a whitespace in their folder name do not display anymore on the ios application.

everything is fine on a webbrowser. 
I can upload from the app to the folder.
I can list the album. I can list all the photos, but the thumbnail have the default picture and the same when I try to see the fullscreen picture.

Everything was fine in a previous version.

looks to me like a quote is missing around a string or something else to escape a space.

**Comment by EddyLB** [comment] 2018-04-13 05:07
Hi,
I have many albums whose names contain one or several white spaces and cannot reproduce the issue. 

Could you please try a different protocol (https instead of https for example) and let me know the outcome ?

**Comment by unnilennium** [comment] 2018-04-13 14:50
Hi EddyLB,
thank you for your quick answer.
I always use https as my webserver only accept https. Will try to see if I can copy it to a test server with only http.
To note I was still using version 2.7.0 and updated to 2.9.3: Same issue.

To precise for the folder name. I have few folders that I thought they had space in their path, but this was only their name in the db. Those are fine. To have the problem you need to have their path having space, like you could get when importing Menalto gallery albums. I have tons of them: few hundreds.

As two examples:
"my holidays 2015" pointing to "./gallery/album789" is fine
"my dogs" pointing to "./gallery/my dogs" will show you the issue... The album is found, but all image links seems broken as I can not get any thumbnails or full photo from those albums. 

One guess I would have is that the path value for every images in those albums is not escaped for spaces as it used to be, or a quote around the full path is missing

**Comment by EddyLB** [comment] 2018-04-13 15:32
Would it be possible to give me a temporary access to test albums ? That would allow me to debug the app and understand the issue.

**Comment by unnilennium** [comment] 2018-04-13 17:00
Do you mean to test my live album ? or when I would be able to set a http test version. 
I have no problem for any of the solutions. I can set a test account for you.

**Comment by unnilennium** [comment] 2018-04-13 18:04
Just sent you a mail with the infos

**Comment by EddyLB** [comment] 2018-04-13 19:51
Thanks for the access.
Indeed, your Piwigo server returns spaces in URLs of thumbnails, etc. and the iOS app gets confused. That will be fixed in the next release.

**Closed** 2018-04-29 11:56 UTC
Labels: Bug
