### ISSUE TITLE
[BUG] Community users cannot upload photos with Piwigo 11.3

### ISSUE THREAD

**Issue by pasaongithub** [Piwigo/Piwigo-Mobile#441] opened 2021-03-03 13:07 UTC
I've configured the Community plugin to add photos to photo gallery without admin permission.
The photo uploading works via desktop browser, but it doesn't work via Piwigo mobile app for iOS (2.5.4 and 2.6 now)
When I try to upload photos from my Photo Library of iPhone
It says:
Uploading... Error
Admin status is required.

I tried to resume the uploads, but this message appears again.

**Expected behavior**
Upload photos successfully.

**What did you do already**
 - I tried to search a similar issue but I cannot find solution. 
 - I try  to set the all things on piwigo demo site https://pasaonpiwigo.piwigo.com, a nono admin user, Community plugin, set the permission an album and upload photos from my phone, but I got the same error, so I can reproduce it on other system too?

**Screenshots**
![image](https://user-images.githubusercontent.com/79169484/109809711-ece68b00-7c28-11eb-9eb9-224c2cdebbdf.png)

My system is:

Piwigo 11.3.0
Operating system: Linux
PHP: 7.3.26 (Show info) [2021-02-14 13:10:06]
MySQL: 5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal [2021-02-14 13:10:06]
Graphics Library: ImageMagick 7.0.10-48

iOS: 14.4
Piwigo mobile app for iOS: 2.5.4, 2.6

Active plugins:
Community: 11.b
LocalFiles Editor 11.3.0
Personal Plugin 1.0
Presync AutoRename 11.1
Upload 1 menu 11.0.a
Virtualize 2.8.a

Inactive plugins:
Admin Tools
Language switch
Take A Tour of Your Piwigo
User Tags

Active themes:
Bootstrap Darkroom
![IMG_3631](https://user-images.githubusercontent.com/79169484/109810333-b4937c80-7c29-11eb-8bab-2c555d199a69.png)

**Comment by EddyLB** [comment] 2021-03-03 18:04
I can reproduce the error and I am surprised that we did not discover it sooner.
The iOS app uses the credentials provided at login, so I guess that the issue is on the server side and I have reported it there. See https://github.com/Piwigo/Piwigo/issues/1356.

**Comment by pasaongithub** [comment] 2021-03-04 07:45
Hi,
A little add-on:
I checked my configuration and my settings is the default, $conf['guest_access'] = true; in the LocalFilesEditor.
Regards,
PaSa

**Comment by EddyLB** [comment] 2021-03-05 17:18
Preliminary investigations shows that this issue will have to be fixed in the [Community plugin](https://github.com/plegall/Piwigo-community/issues/61).
I therefore close this issue.

**Closed by EddyLB** 2021-03-05 17:18 UTC
