### ISSUE TITLE
Cannot upload videos

### ISSUE THREAD

**Issue by czKKill** [Piwigo/Piwigo-Mobile#212] opened 2018-01-08 21:21 UTC
I have a problem uploading videos from iPhone (iOS 11.2.1), app version 2.1.5. (Uploading works from web and Android fine. Uploading pictures works from iOS fine as well.)
After selecting a video, it gets uploaded to the 100% and then throwing an error `unacceptable content type: text/html`. Looks like video is saved in upload/buffer folder without an extension.

I didn't found any error in the logs so far.

Server:
- ubuntu 17.10
- ffmpeg 3.3.4-2
- mediainfo 0.7.98-1
- apache 2.4.27-2ubuntu3, https enabled and hardened (tls1.2 and strong ciphers only)
- latest Piwigo and extensions

Config.inc.php:
```<?php

/* The file does not exist until some information is entered 
below. Once information is entered and saved, the file will be created. */

$conf['upload_form_all_types'] = true;
$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_. ]+$/';

$conf['show_exif'] = true;
$conf['show_exif_fields'] = array(
  'Make',
  'Model',
  'ExifVersion',
  'Software',
  'DateTimeOriginal',
  'FNumber',
  'ExposureBiasValue',
  'FILE;FileSize',
  'ExposureTime',
  'Flash',
  'ISOSpeedRatings',
  'FocalLength',
  'FocalLengthIn35mmFilm',
  'WhiteBalance',
  'ExposureMode',
  'MeteringMode',
  'ExposureProgram',
  'LightSource',
  'Contrast',
  'Saturation',
  'Sharpness',
  'bitrate',
  'channel',
  'date_creation',
  'display_aspect_ratio',
  'duration',
  'filesize',
  'format',
  'formatprofile',
  'codecid',
  'frame_rate',
  'latitude',
  'longitude',
  'make',
  'model',
  'playtime_seconds',
  'sampling_rate',
  'type',
  'resolution',
  'rotation',
  );

// do not serve files using the original path on filesystem
$conf['original_url_protection'] = 'images';
// protect derivates (resized versions), too
$conf['derivative_url_style'] = 2;

// make URLs look better
$conf['question_mark_in_urls'] = false;
//$conf['php_extension_in_urls'] = false;
$conf['category_url_style'] = 'id-name';
$conf['picture_url_style'] = 'id-file';

$conf['slideshow_repeat'] = false;

$conf['log_level'] = 'INFO';

?>
```

Could you please point me to the right direction where the problem might be?

**Comment by EddyLB** [comment] 2018-01-08 22:36
Such an error is returned when the Piwigo server returns an ASCII string instead of the HTTP(S) header expected after a video/image upload.

I suspect that the error is encountered by the VideoJS extension right after the upload, when it is supposed to create a poster from the video.

If I am right, the fix I have proposed some time ago and which is still not implemented in Piwigo might help you. Please see this [pull request](https://github.com/Piwigo/Piwigo/pull/756).

If you can provide me with an access to a test album of your Piwigo, I can run the iOS app in debug mode and determine what is the ASCII message returned by your server.

**Comment by czKKill** [comment] 2018-01-09 18:35
Thanks, I'll try the pull request and let you know the result. 
Meanwhile you'll soon get email with access to my Piwigo for your test.

**Comment by czKKill** [comment] 2018-01-09 19:07
I've applied the pull request (by downloading whole file if that matters anyhow), but still no joy (same error).
Is it possible that it is related to fact that upload is over ipv6 and I see following lines in syslog? I've tried to disable UFW without any effect...

```
Jan  9 19:58:36 piwigo kernel: [152729.097157] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=2 HOPLIMIT=64 FLOWLBL=82743 PROTO=TCP SPT=51475 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
Jan  9 19:58:36 piwigo kernel: [152729.097778] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=0 HOPLIMIT=64 FLOWLBL=82743 PROTO=TCP SPT=51475 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
Jan  9 19:58:36 piwigo kernel: [152729.428894] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=2 HOPLIMIT=64 FLOWLBL=106364 PROTO=TCP SPT=51477 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
Jan  9 19:58:36 piwigo kernel: [152729.428926] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=0 HOPLIMIT=64 FLOWLBL=106364 PROTO=TCP SPT=51477 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
Jan  9 19:58:49 piwigo kernel: [152742.120521] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=2 HOPLIMIT=64 FLOWLBL=338979 PROTO=TCP SPT=51544 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
Jan  9 19:59:09 piwigo kernel: [152761.935546] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=2 HOPLIMIT=64 FLOWLBL=303859 PROTO=TCP SPT=51667 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
Jan  9 19:59:29 piwigo kernel: [152781.883578] [UFW BLOCK] IN=enp0s3 OUT= MAC=08:00:27:8f:47:bb:b4:9c:df:52:a3:2f:86:dd SRC=2001:0470:58c0:0000:0001:ab80:b850:21b2 DST=2001:0470:58c0:0000:0000:0000:0000:0211 LEN=60 TC=2 HOPLIMIT=64 FLOWLBL=1034010 PROTO=TCP SPT=51790 DPT=443 WINDOW=0 RES=0x00 RST URGP=0
```

**Comment by EddyLB** [comment] 2018-01-10 07:31
The iOS app is IPv6 compatible (would have been rejected by Apple if it was not) so I doubt that it is the issue.

Thanks to the credentials you supplied, I could perform some tests with your Piwigo server. When uploading an image, the `pwg.images.upload` API returns the expected JSON answer:

> {
>     result =     {
>         category =         {
>             id = 41;
>             label = Test;
>             "nb_photos" = 3;
>         };
>         "image_id" = 1790;
>         name = "IMG 0003";
>         src = "https://…/i.php/upload/2018/01/10/20180110070702-9de0bcea-th.jpg";
>     };
>     stat = ok;
> }
> 

But with a video (I tried with a MPEG4 file), it returns (null), which is why Piwigo iOS returns the `unacceptable content type: text/html` error. So a method in `functions_upload.inc.php` seems to crash and I have the following questions (probably in the method `upload_file_video()`):

* Is there really nothing in the Piwigo logs (folder `_data/logs`) ? There is a number of `$logger->info()` calls in the function `upload_file_video()` so you should get some logs.
* Have you checked that FFmpeg works as expected? For example, with a video uploaded manually to the server, can you produce a poster of the video with a command like `ffmpeg -ss 00:00:00 -i myVideo.mp4 -frames:v 1 myPoster.jpg` (see [here](https://trac.ffmpeg.org/wiki/Seeking) for explanations)?

**Comment by czKKill** [comment] 2018-01-10 19:24
In the log from today is just this:
```
[2018-01-10 6:51:04]    [INFO]  upload_file_pdf, $file_path = ././upload/2018/01/10/20180110065104-35406317.jpg, $representative_ext =
[2018-01-10 6:51:04]    [INFO]  upload_file_tiff, $file_path = ././upload/2018/01/10/20180110065104-35406317.jpg, $representative_ext =
[2018-01-10 6:51:04]    [INFO]  upload_file_video, $file_path = ././upload/2018/01/10/20180110065104-35406317.jpg, $representative_ext =
[2018-01-10 6:51:04]    [INFO]  Handling ././upload/2018/01/10/20180110065104-35406317.jpg got
[2018-01-10 7:07:02]    [INFO]  upload_file_pdf, $file_path = ././upload/2018/01/10/20180110070702-9de0bcea.jpg, $representative_ext =
[2018-01-10 7:07:03]    [INFO]  upload_file_tiff, $file_path = ././upload/2018/01/10/20180110070702-9de0bcea.jpg, $representative_ext =
[2018-01-10 7:07:03]    [INFO]  upload_file_video, $file_path = ././upload/2018/01/10/20180110070702-9de0bcea.jpg, $representative_ext =
[2018-01-10 7:07:03]    [INFO]  Handling ././upload/2018/01/10/20180110070702-9de0bcea.jpg got
```

FFmpeg is working correctly, posters from uploaded videos via web or [Android app](https://play.google.com/store/apps/details?id=delit.piwigoclient) are generated correctly.
I've generated poster from your video (what got let in buffer folder) successfully:
```
 ffmpeg -ss 00:00:00 -i Test\ —\ Vidéo\  -frames:v 1 myPoster.jpg
ffmpeg version 3.3.4-2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.2.0-8ubuntu2)
  configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse
--enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Test — Vidéo ':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2018-01-10T05:59:40.000000Z
    location        : +45.1694+005.7123+250.431000/
  Duration: 00:00:00.97, start: 0.000000, bitrate: 15946 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 15851 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      creation_time   : 2018-01-10T05:59:40.000000Z
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 75 kb/s (default)
    Metadata:
      creation_time   : 2018-01-10T05:59:40.000000Z
      handler_name    : Core Media Audio
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x55adf73076c0] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'myPoster.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    location        : +45.1694+005.7123+250.431000/
    encoder         : Lavf57.71.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2018-01-10T05:59:40.000000Z
      handler_name    : Core Media Video
      encoder         : Lavc57.89.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    1 fps=0.0 q=8.4 Lsize=N/A time=00:00:00.03 bitrate=N/A speed=0.0726x
video:156kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

Btw I'm using PHP 7.1.11-0ubuntu0.17.10.1. What remindes me that I did some hardening on php as well (but don't really recall the details as it was some time ago), ie this:
```
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
allow_url_fopen = On
allow_url_include = Off
```
Will it help you if I would upload whole php.ini here?

**Comment by EddyLB** [comment] 2018-01-10 21:25
Can you please replace the PHP file "functions_upload.inc.php" in admin/include with the one you will find in [Script+Log.zip](https://github.com/Piwigo/Piwigo-Mobile/files/1620497/Script.Log.zip) (please keep a backup by renaming the existing one)? Then, try to upload a video recorded with your iPhone to your Piwigo server and send me the corresponding log. You should get logs similar to those attached.

**Comment by czKKill** [comment] 2018-01-10 21:49
I didn't get anything - what is probably the problem.
I've even enabled debug (`$conf['log_level'] = 'DEBUG';`). When I upload picture I get the entries but nothing for video.

So the php die somehow before executing ffmpeg without actually logging anything.

Out of the interest I tried it from Android and I get similar entries like we need:
```
[2018-01-10 22:38:57]   [DEBUG] [WS]    ws_images_exist
  md5sum_list: '77a757d2d61011aeed2b0e6e80595d72'
  filename_list: NULL
[2018-01-10 22:38:59]   [INFO]  upload_file_pdf, $file_path = ././upload/2018/01/10/20180110223859-77a757d2.mp4, $representative_ext =
[2018-01-10 22:38:59]   [INFO]  upload_file_tiff, $file_path = ././upload/2018/01/10/20180110223859-77a757d2.mp4, $representative_ext =
[2018-01-10 22:38:59]   [INFO]  upload_file_video, $file_path = ././upload/2018/01/10/20180110223859-77a757d2.mp4, $representative_ext =
[2018-01-10 22:38:59]   [DEBUG] upload_file_video, Prepare directory at ././upload/2018/01/10/pwg_representatives
[2018-01-10 22:39:00]   [DEBUG] upload_file_video, Poster will be produced at 2s
[2018-01-10 22:39:01]   [DEBUG] upload_file_video, Tried ffmpeg -ss 2 -i "././upload/2018/01/10/20180110223859-77a757d2.mp4" -frames:v 1 "././upload/2018/01/10/pwg_representative/20180110223859-77a757d2.jpg"
[2018-01-10 22:39:01]   [DEBUG] ffmpeg version 3.3.4-2 Copyright (c) 2000-2017 the FFmpeg developers
[2018-01-10 22:39:01]   [INFO]  Handling ././upload/2018/01/10/20180110223859-77a757d2.mp4 got jpg
[2018-01-10 22:39:01]   [DEBUG] [WS]    ws_images_checkFiles
  file_sum: '77a757d2d61011aeed2b0e6e80595d72'
  image_id: 1792
  thumbnail_sum: NULL
  high_sum: NULL
[2018-01-10 22:39:01]   [DEBUG] [WS]    ws_images_checkFiles, md5_file($path) = 77a757d2d61011aeed2b0e6e80595d72
[2018-01-10 22:39:01]   [DEBUG] [WS]    ws_images_checkFiles
  file: 'equals'
```

Checking the access.log looks like iPhone app is using `POST /ws.php?format=json&method=pwg.images.upload HTTP/1.1` but Android just `POST /ws.php?format=json HTTP/1.1` - can this play any role?
Also post sizes vary on Android.

Full logs for reference:
iPhone
```
2001:470:58c0:0:1 - - [10/Jan/2018:22:33:28 +0100] "POST /ws.php?format=json&method=pwg.images.upload HTTP/1.1" 200 3936 "-" "piwigo/2.1.5 (iPhone; iOS 11.2.1; Scale/2.00)"
2001:470:58c0:0:1 - - [10/Jan/2018:22:33:28 +0100] "POST /ws.php?format=json&method=pwg.images.upload HTTP/1.1" 200 3936 "-" "piwigo/2.1.5 (iPhone; iOS 11.2.1; Scale/2.00)"
2001:470:58c0:0:1 - - [10/Jan/2018:22:33:29 +0100] "POST /ws.php?format=json&method=pwg.images.upload HTTP/1.1" 200 3936 "-" "piwigo/2.1.5 (iPhone; iOS 11.2.1; Scale/2.00)"
2001:470:58c0:0:1 - - [10/Jan/2018:22:33:29 +0100] "POST /ws.php?format=json&method=pwg.images.upload HTTP/1.1" 200 3936 "-" "piwigo/2.1.5 (iPhone; iOS 11.2.1; Scale/2.00)"
```
Android
```
192.168.0.22 - - [10/Jan/2018:22:36:37 +0100] "POST /ws.php?format=json HTTP/1.1" 200 3469 "-" "Apache-HttpClient/UNAVAILABLE (java 1.5)"
192.168.0.22 - - [10/Jan/2018:22:36:37 +0100] "POST /ws.php?format=json HTTP/1.1" 200 741 "-" "Apache-HttpClient/UNAVAILABLE (java 1.5)"
192.168.0.22 - - [10/Jan/2018:22:36:37 +0100] "POST /ws.php?format=json HTTP/1.1" 501 420 "-" "Apache-HttpClient/UNAVAILABLE (java 1.5)"
192.168.0.22 - - [10/Jan/2018:22:36:37 +0100] "POST /ws.php?format=json HTTP/1.1" 200 761 "-" "Apache-HttpClient/UNAVAILABLE (java 1.5)"
```

**Comment by EddyLB** [comment] 2018-01-11 06:06
Can you please disable the PHP restrictions you've set in your server and tell what happens?

**Comment by czKKill** [comment] 2018-01-11 19:46
I've restored default php.ini ([here](https://github.com/Piwigo/Piwigo-Mobile/files/1623907/php.zip)), only with this customization in .htaccess file:
```
php_value upload_max_filesize 1G
php_value post_max_size 1G
php_value max_file_uploads 20
```
Same result.

**Comment by EddyLB** [comment] 2018-01-11 22:08
In order to try to find where the Piwigo server PHP script dies, I have prepared a version of the file `pwg.images.php` that will output logs in the Apache `error.log` file. Please download  [Script+ApacheLog.zip](https://github.com/Piwigo/Piwigo-Mobile/files/1624295/Script.ApacheLog.zip) and try.

**Comment by czKKill** [comment] 2018-01-12 19:53
[Here it is](https://github.com/Piwigo/Piwigo-Mobile/files/1627282/error.log)
Last few lines:
```
[2018-01-12T20:49:24+01:00] ws_images_upload, IMG_1884 245/246
File OUT: Resource id #16 closed, File IN: Resource id #17 closed
Check if file has been uploadedâ€¦
[2018-01-12T20:49:24+01:00] ws_images_upload

$_FILES = array (
  'file' => 
  array (
    'name' => 'IMG_1884.mp4',
    'type' => 'video/mp4',
    'tmp_name' => '/tmp/phpFy6tKW',
    'error' => 0,
    'size' => 322944,
  ),
)
$_POST = array (
  'name' => 'IMG_1884',
  'chunk' => '245',
  'chunks' => '246',
  'category' => '41',
  'level' => '0',
  'pwg_token' => 'c53f763f2221b569d7c658808169e18b',
)
[2018-01-12T20:49:24+01:00] ws_images_upload, IMG_1884 246/246
File OUT: Resource id #16 closed, File IN: Resource id #17 closed
Check if file has been uploadedâ€¦
```

**Comment by EddyLB** [comment] 2018-01-12 22:07
Thank you. So there is clearly an issue on your server because the PHP script crashes well before replying to the HTTP request (and Piwigo iOS receives (null)).
I now invite you to replace the 2 scripts with those provided in [Scripts+ApacheLog2+PiwigoLog.zip](https://github.com/Piwigo/Piwigo-Mobile/files/1627630/Scripts.ApacheLog2.PiwigoLog.zip), upload a short video (2s duration is well enough) and send me the Apache error.log and Piwigo log you obtained.

**Comment by czKKill** [comment] 2018-01-13 13:22
Well I thank **you** in first place for taking the time to help me debug the issue.
[Here is the error.log](https://github.com/Piwigo/Piwigo-Mobile/files/1628375/error.log)

Piwigo log is shorter and more useful I guess:
```
[2018-01-13 14:15:42]   [INFO]  add_uploaded_file, $source_filepath = ./upload/buffer/IMG_1908
[2018-01-13 14:15:42]   [INFO]  add_uploaded_file, $original_filename = IMG_1908
[2018-01-13 14:15:42]   [INFO]  add_uploaded_file, $md5sum = b2fb28f61d1ee073daf52fb4588ac30f
[2018-01-13 14:15:42]   [INFO]  add_uploaded_file, this photo is new
[2018-01-13 14:15:42]   [INFO]  add_uploaded_file, $upload_dir = ././upload/2018/01/13
[2018-01-13 14:15:42]   [INFO]  add_uploaded_file, unexpected file type
```

I guess the last line is the real problem, but shouldn't this be mitigated by this?
```
$conf['upload_form_all_types'] = true;
$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_. ]+$/';
```

**Comment by EddyLB** [comment] 2018-01-14 07:35
The problem is that the `$original_filename` has no extension and the Piwigo function `add_uploaded_file` does not know what to do with the uploaded file. This is clearly visible in the second line of the Piwigo log.

We can also see in the Apache logs that the `name` key of the `$_POST` array  does not have an extension.

```
$_FILES = array (
  'file' => 
  array (
    'name' => 'IMG_1908.mp4',
    'type' => 'video/mp4',
    'tmp_name' => '/tmp/phpBwLpoE',
    'error' => 0,
    'size' => 512000,
  ),
)
$_POST = array (
  'name' => 'IMG_1908',
  'chunk' => '0',
  'chunks' => '14',
  'category' => '41',
  'level' => '0',
  'pwg_token' => 'd52cf32543689915d93ea5c126bb44ae',
)
```

I will have a look at the Piwigo PHP code and will let you know as I soon as I can because I am travelling for my (real) work.

**Comment by czKKill** [comment] 2018-01-14 07:41
thanks, safe travels

**Comment by EddyLB** [comment] 2018-01-16 21:12
While I'm travelling, could you please:

1. put back the original php files,
2. replace the script `rest_handler.php` located in the folder `include/ws_protocols` with [this one](https://github.com/Piwigo/Piwigo-Mobile/files/1636841/rest_handler.php.zip),
3. upload an image
4. upload a video
5. provide the entire Apache logs of these two uploads, i.e. the series of `handleRequest` logs as follows:
```
[2018-01-16T21:59:45+01:00] handleRequest

$_FILES = array (
  'file' => 
  array (
    'name' => 'IMG_0017.mp4',
    'type' => 'video/mp4',
    'tmp_name' => '/tmp/phpMTFq5c',
    'error' => 0,
    'size' => 512000,
  ),
)
$_POST = array (
  'name' => 'IMG_0017.mp4',
  'chunk' => '0',
  'chunks' => '4',
  'category' => '469',
  'level' => '4',
  'pwg_token' => 'd98491f456ddd79319d74cbaf0aed6b1',
)
$param_array = array (
  'name' => 'IMG_0017.mp4',
  'chunk' => '0',
  'chunks' => '4',
  'category' => '469',
  'level' => '4',
  'pwg_token' => 'd98491f456ddd79319d74cbaf0aed6b1',
)
$method = 'pwg.images.upload'
$params = array (
  'name' => 'IMG_0017.mp4',
  'chunk' => '0',
  'chunks' => '4',
  'category' => '469',
  'level' => '4',
  'pwg_token' => 'd98491f456ddd79319d74cbaf0aed6b1',
)

```

**Comment by czKKill** [comment] 2018-01-19 20:04
Here it is:
[error_image.log](https://github.com/Piwigo/Piwigo-Mobile/files/1647783/error_image.log)
[error_video.log](https://github.com/Piwigo/Piwigo-Mobile/files/1647784/error_video.log)

**Comment by EddyLB** [comment] 2018-01-21 12:32
Thank you for these logs. There is indeed a bug in the iOS app which prevents the upload of videos with some servers. I have now fixed it and I can upload videos to your server in the Test album. However, the production of the poster does not work.
Can you please check that the fix I have proposed in this [pull request](https://github.com/Piwigo/Piwigo/pull/756) is installed on your server? Can you provide the logs?

**Comment by czKKill** [comment] 2018-01-21 19:37
> Can you please check that the fix I have proposed in this pull request is installed on your server?

It wasn't as I reverted all files to original. I've put the fix there, but problem is in settings as I have `Create a poster at position in second: 4` so I presume your video is too short.

And in the logs is (as expected I guess):
```
[2018-01-21T17:32:50+01:00] handleRequest

$param_array = array (
  'format' => 'json',
  'method' => 'pwg.categories.getList',
  'cat_id' => '1',
  'recursive' => 'true',
  'faked_by_community' => 'true',
)
$method = 'pwg.categories.getList'
$params = array (
  'cat_id' => '1',
  'recursive' => 'true',
  'faked_by_community' => 'true',
)
identify-im6.q16: insufficient image data in file `/var/www/html/upload/2018/01/21/pwg_representative/20180121132100-e85e1173.jpg' @ error/jpeg.c/ReadJPEGImage/1039.
identify-im6.q16: insufficient image data in file `/var/www/html/upload/2018/01/21/pwg_representative/20180121131509-9479a234.jpg' @ error/jpeg.c/ReadJPEGImage/1039.

ffmpeg version 3.3.4-2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.2.0-8ubuntu2)
  configuration: --prefix=/usr --extra-version=2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse
--enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[NULL @ 0x559a5faf4940] Unable to find a suitable output format for '/dev/null'
/dev/null: Invalid argument
identify-im6.q16: insufficient image data in file `/var/www/html/upload/2018/01/21/pwg_representative/20180121131509-9479a234.jpg' @ error/jpeg.c/ReadJPEGImage/1039.
identify-im6.q16: insufficient image data in file `/var/www/html/upload/2018/01/21/pwg_representative/20180121132100-e85e1173.jpg' @ error/jpeg.c/ReadJPEGImage/1039.
```

**Comment by EddyLB** [comment] 2018-01-21 19:40
If you apply the fix I have proposed in the [pull request](https://github.com/Piwigo/Piwigo/pull/756), the short duration of the video will be taken into account.

**Comment by czKKill** [comment] 2018-01-21 19:44
Can you upload the video again to test it please? (I've deleted the old one)

**Comment by EddyLB** [comment] 2018-01-21 19:47
That now works perfectly ;-)
Many thanks for having raised the issue and helped me fixing this bug…

**Comment by czKKill** [comment] 2018-01-21 19:51
Awsome!
Thank you very much for your effort. So now I should wait for the new version of iOS app and then we can upload all the videos we want? :-)

Out of curiosity - what is special on my server that triggered this bug if I may ask?

**Comment by EddyLB** [comment] 2018-01-21 20:17
I am preparing the next release 2.1.7 and will try to submit it this week for TestFlight testing.

With regard this bug, I have realised that the code (used since 2015) wrongly provides the image title as file name in the `pwg.images.upload` API call. I guess that this error comes from the fact that the key of the filename of the `pwg.images.upload` API is identical to the one of image titles for other API methods like `pwg.image.setInfo` (confusing, isn't it?).
Because the iOS app was using the filename as default title, only some of the people changing the title encountered an issue. Recently, I changed this default behaviour so that the proposed title is the file name without extension and that has increased the probability to encounter the bug. What surprises me is that a number of people, including me, did not encounter the problem, as if the extension of the file was added by an app of the server. Strange…

**Comment by czKKill** [comment] 2018-01-22 22:57
Strange indeed, maybe some another plugin or patches? Hard to say I guess. Anyway thank you for explanation.

**Comment by EddyLB** [comment] 2018-01-27 12:54
The updated app is now available for TestFlight testing.
Can you please confirm that this issue is fixed?

**Comment by czKKill** [comment] 2018-01-27 18:45
I'm not sure how's that working as iPhone is actually used by my wife, but it looks like I need some invitation from you to be able to install new version..?

**Comment by EddyLB** [comment] 2018-01-27 18:53
You will need the [TestFlight](https://itunes.apple.com/us/app/testflight/id899247664?mt=8) app (free) and an invitation from me. I've sent one to your email address mic…@mal….in.

**Comment by czKKill** [comment] 2018-01-27 18:56
I've tested it and it's working!

Thank you very much

**Comment by hencisk** [comment] 2019-09-29 14:47
Hello!
Could be, that old issue with video uploads is back?
Having error "unacceptable-content-type: text/html" from IOS Piwigo 2.4.3, when uploading video to Piwigo server 2.9.5.
Did a troubleshooting applying modified php files for debug output from article above and seems getting similar issue, or file without extension in post method.
Apache log:
[2019-09-29T17:32:50+03:00] ws_images_upload

$_FILES = array (
  'file' => 
  array (
    'name' => 'IMG_0169.mp4',
    'type' => 'video/mp4',
    'tmp_name' => '/tmp/phpOc2GWU',
    'error' => 0,
    'size' => 149983,
  ),
)
$_POST = array (
  'name' => 'IMG_0169',
  'chunk' => '75',
  'chunks' => '76',
  'category' => '469',
  'level' => '0',
  'pwg_token' => '3e3017970cd058f4ab2a03916463d8a1',
)
[2019-09-29T17:32:50+03:00] ws_images_upload, IMG_0169 76/76
File OUT: Resource id #87 closed, File IN: Resource id #88 closed
Check if file has been uploaded...
Try: remove .part suffix of ./upload/buffer/IMG_0169...
Try: include_once(./admin/include/functions_upload.inc.php)...
Try: image_id = add_uploaded_file(...

Piwigo log:
[2019-09-29 17:32:50]   [INFO]  add_uploaded_file, $source_filepath = ./upload/buffer/IMG_0169
[2019-09-29 17:32:50]   [INFO]  add_uploaded_file, $original_filename = IMG_0169
[2019-09-29 17:32:50]   [INFO]  add_uploaded_file, $md5sum = 8fce21ac194534df7fe77ca5ce632a9d
[2019-09-29 17:32:50]   [INFO]  add_uploaded_file, this photo is new
[2019-09-29 17:32:50]   [INFO]  add_uploaded_file, $upload_dir = ././upload/2019/09/29
[2019-09-29 17:32:51]   [INFO]  add_uploaded_file, unexpected file type

**Comment by EddyLB** [comment] 2019-09-29 17:16
Oups! Good point. Sorry for the troubles.
I have concentrated on the issues encountered with empty titles and forgot this problem with videos.

**Comment by hencisk** [comment] 2019-10-03 07:07
Video upload works now, like a charm! Thank you very match!

**Closed** 2019-10-03 07:38 UTC
Labels: Bug

**Comment by EddyLB** [comment] 2019-10-03 07:48
Thank you.

**Comment by baomin** [comment] 2021-09-23 11:38
good！！！
